### ISSUE TITLE
python3_host_prog must be defined before activating sourcing Plugin

### ISSUE THREAD

**Issue by thraizz** [a-vrma/black-nvim#2]
This is not much of an issue but more like a hint for other users:
If you use this plugin with vim-plug then you have to define `let g:python3_host_prog = $HOME . '/.local/venv/nvim/bin/python'` **before**  calling `Plug 'a-vrma/black-nvim', {'do': ':UpdateRemotePlugins'}`, otherwise the `:UpdateRemotePlugins` runs in a wrong python environment, resulting in a `E127: Unkown Function: Black`.

**Comment by averms** [comment]
I'll add this to the README.
